### ISSUE TITLE
Test CommandBehavior.SingleResult, SingleRow

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/AdoNetApiTest#39]
From [CommandBehavior Enum](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=netframework-4.8):

> * `SingleResult`: The query returns a single result set.
> * `SingleRow`: The query is expected to return a single row of the first result set. … Some .NET Framework data providers may, but are not required to, use this information to optimize the performance of the command. … It is possible to specify SingleRow when executing queries that are expected to return multiple result sets. In that case, where both a multi-result set SQL query and single row are specified, the result returned will contain only the first row of the first result set. The other result sets of the query will not be returned.

Does calling `DbDataReader.Read` return `false` after the first row is returned? Does `DbDataReader.NextResult` return `false` after the first result set?

**Comment by roji** [comment]
That is certainly the Npgsql behavior (see [this test](https://github.com/npgsql/npgsql/blob/9deeb37d5c28117de10daecc692cbed22c00be7b/test/Npgsql.Tests/CommandTests.cs#L421) and [this test](https://github.com/npgsql/npgsql/blob/8691e2650dace5bf88bfb18505f7ba4c452037b5/test/Npgsql.Tests/ReaderTests.cs#L582). Otherwise we'd Read/NextResult would return true but actually accessing anything would throw, which seems quite bad.

But seems worth confirming the SqlClient behavior...

**Comment by roji** [comment]
I agree that these are optional, but if they *are* honored then Read and NextResult should return false after the first thing, right? In other words, they can either be totally ignored (and return multiple rows/resultsets), or the methods must return false...

(at least this is how I understood @bgrainger's question)

**Comment by bgrainger** [comment]
Tested in 7d92273a0c8d7576fa40d3b066ba7c83bd90c960 and 78507518cf52bd45a131a6021b3f406edac4ad13.
